/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layer1;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author User
 */
public class coba2 extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet rs;
    public PreparedStatement pst;
    private Statement st;
    private DefaultTableModel dtm;
    /**
     * Creates new form coba2
     */
    
    private void kosongkan(){
        kodetxt.setText(null);
        //text di kode jadi kosong
        namatxt.setText(null);
        //text di nama jadi kosong
        hargatxt.setText(null);
        //text di harga jadi kosong
        stoktxt.setText(null);
        //text di stok jadi kosong
        
    }
    public coba2() throws SQLException {
        initComponents();
          conn = null;
        conn = DriverManager.getConnection("jdbc:mysql://localhost/test","root","");
        //untuk koneksi ke mysqlnya
        UpdateTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodetxt = new javax.swing.JTextField();
        hargatxt = new javax.swing.JTextField();
        stoktxt = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        update = new javax.swing.JButton();
        namatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SHOW = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        member = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "kode", "nama buah", "harga", "stok"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel1.setText("kode");

        jLabel2.setText("stok");

        jLabel3.setText("nama");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        namatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatxtActionPerformed(evt);
            }
        });

        jLabel4.setText("harga");

        SHOW.setText("Show");
        SHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWActionPerformed(evt);
            }
        });

        clean.setText("Clean");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });

        member.setText("Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stoktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(member)))
                                .addGap(10, 10, 10)
                                .addComponent(logout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(member)
                            .addComponent(logout))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(clean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stoktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
       try
            {
                String sql = "update buah set kode=?, harga=?, stok=? where kode='"+kodetxt.getText()+"'";
                //mengupdate database buah yang mana kode = kode teks
                PreparedStatement st=conn.prepareStatement(sql);
               //pengiriman statement SQL 
                {
                try
                    {
                        st.setString(1,kodetxt.getText());
                        st.setString(2,hargatxt.getText());
                        st.setString(3,stoktxt.getText());
                        
                        //ngambil teks yang ada di kode harga stok
                        st.executeUpdate();
                        //mengeksekusi query yang tidak menghasilkan apapun, misal INSERT, UPDATE, DELETE
                        UpdateTabel();
                        //menampilkan tabel sql lagi
                        

                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                        // kotak pesan "Update Data Sukses"
                    }catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                       // kotak pesan "Update Data Gagal"
                    }
                }
           }catch (Exception e)
           {}
       
    }//GEN-LAST:event_updateMouseClicked

    private void SHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWActionPerformed
        // TODO add your handling code here:
        try
            {
                String sql="select * from buah where kode='" + kodetxt.getText() + "'";
                //pilih semua dari buah yang mana kode sama dengan kode teks
                st=conn.createStatement();
                rs=st.executeQuery(sql);

                while(rs.next())
                {
                    kodetxt.setText(rs.getString("kode"));
                    //menampilkan kode dari tabel buah di mysql
                    namatxt.setText(rs.getString("nama buah"));
                    //menampilkan nama buah dari tabel buah di mysql
                    hargatxt.setText(rs.getString("harga"));
                    //menampilkan harga dari tabel buah di mysql
                    stoktxt.setText(rs.getString("stok"));
                    //menampilkan stok dari tabel buah di mysql
                    
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"GAGAL");
                // kotak pesan "Update Data Gagal"
            }         
    }//GEN-LAST:event_SHOWActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_cleanActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
new login().setVisible(true);
//menampikan class login
            //perintah exit keluar
    }//GEN-LAST:event_logoutActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        try {
            // TODO add your handling code here:
            new coba3().setVisible(true);
            //menampilkan kelas coba3
        } catch (SQLException ex) {
            Logger.getLogger(coba2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memberActionPerformed

    private void namatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatxtActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed
private void UpdateTabel() {
   // menampilkan tabel buah ke tabel jframe
        try {
            String sql = "SELECT * FROM buah;";
            //pilih semua dari buah
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) tabel.getModel();
        dtm.setRowCount(0);
        String [] data = new String[6];
        int i = 1;
       
        while(rs.next()) {
            data[0] = rs.getString("kode");
            data[1] = rs.getString("nama buah");
            data[2] = rs.getString("harga");
            data[3] = rs.getString("stok");
            dtm.addRow(data);
            i++;
        }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) throws Exception{
                new coba2().setVisible(true);
            }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SHOW;
    private javax.swing.JButton clean;
    private javax.swing.JTextField hargatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodetxt;
    private javax.swing.JButton logout;
    private javax.swing.JButton member;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField stoktxt;
    private javax.swing.JTable tabel;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
